# action.yml
name: 'Build MyApp'
description: 'Build a python package and RPM from this repo.'
outputs:
  python_dist: # id of output
    description: 'The path to python sdist and wheel.'
  srpm_dir:
    description: 'Output directory for SRPM.'
  rpm_dir:
    description: 'Output directory for RPM.'
runs:
  using: 'docker'
  image: 'docker.io/dpfulton/suse-python-rpmbuild:latest'
  entrypoint: 'entrypoint.sh'
